### ISSUE TITLE
Get data to be compatible with 'biotic'

### ISSUE THREAD

**Issue by robbriers** [alexology/biomonitoR#7]
Looking at the way in which the data are structured in 'biomonitoR', it should be simple enough to convert into a format that is suitable to run through 'biotic'. The following seems to work:

```
library(biomonitoR)
library(biotic)
class_details <- aggregatoR(asBiomonitor(macro_ex))
for_calc<-class_details$Family
bmwp <- calcBMWP(for_calc)
bmwp
```

**Comment by alexology** [comment]
I agree, it should be very easy. I have to check the issue about Oligochaeta. As far as I know it is the only taxon for which the taxonomic level of order is allowed. Does the package biotic accept Oligochaeta as order? This could be a problem when users import Oligochaeta at order level in biomonitoR, since class_details$Family should exclude them.

Thank you!

**Comment by robbriers** [comment]
Oligochaetes are the only group that is accepted at higher taxonomic level by `biotic.` The `convertobiotic` function works great when I tested it. Good job! I will aim to incorporate a reverse function when I next update `biotic`
